Assign = (FuncAssing | VarAssing).
VarAssing = VarName "=" (Evalution | Collection).
FuncAssing = VarName "(" VarName {";" VarName} ")" "=" Evalution.
Collection = (Set | Tuple).
Set = "{" {SetComp {"," SetComp}} "}".
SetComp = (Literal | Tuple).
Tuple = "[" Literal "," Literal {"," Literal} "]".
Evalution = ("(" Evalution ")" | Prefix Evalution | Evalution Operator Evalution | Evalution Suffix | Literal).
Prefix = "-".
Suffix = "!".
Operator = ("+" | "-" | "*" | "/" | "%").
Literal = (VarName | Number).
Number = Digit {Digit0} ("." | "") {Digit0}.
VarName = Character {(Character | Digit)}.
Digit = (Digit0 | "0").
Digit0 = ("1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9").
Character = ("A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | 
				"J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | 
				"T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | 
				"d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | 
				"n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" |
				"x" | "y" | "z").